# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: psc

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: psc
    binary: psc
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: psc
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

nfpms:
  - id: psc
    package_name: psc
    vendor: loresuso
    homepage: https://github.com/loresuso/psc
    maintainer: loresuso
    description: Process and container inspector using eBPF
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/psc/LICENSE
      - src: README.md
        dst: /usr/share/doc/psc/README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: loresuso
    name: psc
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

